include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

.vars-devel:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    MANIFEST_PATH: "flatpak/net.figuiere.Niepce.Devel.json"
    FLATPAK_MODULE: "niepce"
    APP_ID: "net.figuiere.Niepce.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "niepce-dev.flatpak"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

rust-fmt:
  image: "registry.gitlab.com/alatiera/rustfmt-oci-image/rustfmt:stable"
  needs: []
  script:
    - echo -e "" > niepce-main/src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo --version
    - cargo fmt --all -- --check

# Build Flatpak for x86_64
flatpak@x86_64:
  extends: ['.flatpak@x86_64', '.vars-devel']

# Build Flatpak for aarch64
flatpak@aarch64:
  extends: ['.flatpak@aarch64', '.vars-devel']

#nightly@x86_64:
#  extends: '.publish_nightly'
#  # assuming your job in named 'flatpak@x86_64'
#  needs: ['flatpak@x86_64']

#nightly@aarch64:
#  extends: '.publish_nightly'
#  # assuming your job in named 'flatpak@aach64'
#  needs: ['flatpak@aarch64']
