[package]
name = "npc-craw"
version = "0.1.0"
edition = "2021"
description = "Niepce Camera Raw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "*"
cxx = { version = "1.0", features = [ "c++17" ] }
gdk-pixbuf = "*"
gdk-pixbuf-sys = "*"
gdk4 = "*"
glib = "*"
gtk4 = "^0.6"

npc-fwk = { path = "../npc-fwk" }
npc-engine = { path = "../npc-engine" }

[build-dependencies]
pkg-config = "0.3.26"
