[package]
name = "npc-craw"
version = "0.1.0"
edition = "2021"
description = "Niepce Camera Raw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "*"
cxx = { version = "1.0", features = [ "c++17" ] }
glib = "*"
gtk4 = "^0.6"
